apiVersion: v1
kind: ServiceAccount
metadata:
  name: steerd-presto-operator
  namespace: default

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: steerd-presto-operator
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "services", "events", "services/finalizers", "endpoints", "persistentvolumeclaims", "configmaps", "secrets"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["*"]
  - apiGroups: ["falarica.io"]
    resources: ["prestos", "prestos/status"]
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: steerd-presto-operator
  namespace: default
subjects:
  - kind: ServiceAccount
    namespace: default
    name: steerd-presto-operator
roleRef:
  kind: ClusterRole
  name: steerd-presto-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steerd-presto-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: steerd-presto-operator
  template:
    metadata:
      labels:
        name: steerd-presto-operator
    spec:
      serviceAccountName: steerd-presto-operator
      containers:
        - name: steerd-presto-operator
          # Replace this with the built image name
          image: falarica/steerd-presto-operator:0.1
          command: [ "/bin/steerd-presto-operator" ]
          imagePullPolicy: Always
